### ISSUE TITLE
Pre built APK and saving sleep stages to file

### ISSUE THREAD

**Issue by MarcusRobbins** [AbhayKoushik/RealTimeSleepStaging#1]
Hi,
I was just thinking about trying to do something like this myself, all be it using an existing NN for classification.
Is there any chance you could include a prebuilt APK?

Also is it possible to output the sleep stage classification to a file for post analysis?
I have had a quick look at the code and this seems to be commented out, is that right?

Great work btw. This might help me get to the bottom of why I'm so damn tired all the time!

(Edited because I see there is a pre-trained NN)

**Comment by AbhayKoushik** [comment]
> Hi,
> I was just thinking about trying to do something like this myself, all be it using an existing NN for classification.
> Is there any chance you could include a prebuilt APK?
> 
> Also is it possible to output the sleep stage classification to a file for post analysis?
> I have had a quick look at the code and this seems to be commented out, is that right?
> 
> Great work btw. This might help me get to the bottom of why I'm so damn tired all the time!
> 
> (Edited because I see there is a pre-trained NN)

Hi Marcus,

Please go through our README.md to find all your queries resolved. We already have the pre-built apk and a functional file-writing system included in our app.

Thanks for your comments - This work is currently trained and tested only on the pre-existing Sleep-EDF dataset and adapted onto the Muse - wearable Brain-Computer-Interface form-factor. I encourage you to go through our papers and cite them if you find them helpful. Have fun hacking around!

PS: Feel free to get back in case you have further queries, closing this issue for now as it's resolved. Thanks!

**Comment by MarcusRobbins** [comment]
Hi,

Where is the apk file in the repository? I am unable to see it.

Thanks,
Marcus

**Comment by AbhayKoushik** [comment]
> Hi,
> 
> Where is the apk file in the repository? I am unable to see it.
> 
> Thanks,
> Marcus

Just added the path: /build/outputs where you can find it, I'd forgotten to update my .gitignore - thanks for mentioning!
