### ISSUE TITLE
Encoding scheme

### ISSUE THREAD

**Issue by ibneturabhassan** [AbhayKoushik/RealTimeSleepStaging#2]
I am trying to run code from you repository. When I run prepare_physionet.py it shows this error message.
**UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 2110: character maps to <undefined>**

Can you please confirm which encoding scheme was used when you ran this code?

**Comment by AbhayKoushik** [comment]
Thanks for reaching out Hassan, it's generally a good practice to describe the full traceback of your error to ensure a speedy fix-

But with the limited information I see here, it might help you to refer to where we adapted our pre-processing code from: [akaraspt/deepsleepnet](https://github.com/akaraspt/deepsleepnet/blob/master/prepare_physionet.py)

Let me know if the encoding scheme specified there resolves your issue.

**Comment by AbhayKoushik** [comment]
Closing this issue as it has been inactive for a few months. Probably means that it is not reproducible or might have been fixed locally.

Please reopen if you still encounter this issue. Thanks!
